name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозиторію
      uses: actions/checkout@v4

    - name: Перевірка наявності README.md
      run: |
        if [ ! -f README.md ]; then
          echo "README.md не знайдено!"
          exit 1
        fi
